name: preto-branco-xai
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - lime
      - shap
